# # -*- coding: utf-8 -*-
# """Stock Market Analysis Time Series Analysis and Forecasting.ipynb
# 
# Automatically generated by Colaboratory.
# 
# Original file is located at
#     https://colab.research.google.com/drive/1i18gzCmP4zvvKzWB0HxVd3N94KMFSQUw
# 
# ### **Loading Libraries**
# """

if(!require(quantmod)) install.packages("quantmod")
if(!require(forecast)) install.packages("forecast")
if(!require(xlsx)) install.packages("xlsx")
if(!require(timeSeries)) install.packages("timeSeries")
if(!require(dplyr)) install.packages("dplyr")
if(!require(tsfknn)) install.packages("tsfknn")
library(tidyverse)
library(quantmod)
library(forecast)
library("xlsx")
library(timeSeries)
library(dplyr)
library(tsfknn)
library(ggplot2 )

# """### **Getting Stock Data**"""

gsachs <- getSymbols("GS", src = "yahoo", from = "2016-01-01", to = as.character(Sys.Date()), auto.assign = FALSE)
dim(gsachs)
summary(gsachs)
tail(gsachs)

# """###**Stock Return Behaviour using logarithm properties to calculate the log-return of the stock**"""

gsachs_ret <- diff(log(gsachs[,6]))
gsachs_ret <- gsachs_ret[-1,]
options(repr.plot.width = 25, repr.plot.height = 10)
ggplot(gsachs_ret, aes(x = index(gsachs_ret), y = gsachs_ret)) +
  geom_line(color = "deepskyblue4") +
  ggtitle("Goldman Sachs Group Inc returns series") +
  xlab("Date") + ylab("Return") +
  theme(plot.title = element_text(hjust = 0.5)) + scale_x_date(date_labels = "%b %y", date_breaks = "6 months")

# """### **Forecasting Using ARIMA Model**"""

modelfit <- auto.arima(Cl(gsachs), lambda = "auto")
modelfit
price_forecast <- forecast(modelfit, h=30)
options(repr.plot.width = 30, repr.plot.height = 10)
plot(price_forecast) # Blue Line = represents the mean of prediction

# """### **Forecasting Using K Nearest Neighbours**"""

gsachs_df <- data.frame(date = index(gsachs), close = as.numeric(gsachs[,'GS.Close']))
head(gsachs_df)
tail(gsachs_df)

gsachs_knn <- knn_forecasting(gsachs_df$close, h = 30, lags = 1:30, k = 40, msas = "MIMO")

ro <- rolling_origin(predknn)  #accuracy
print(ro$global_accu)          #accuracy

plot(gsachs_knn)

# """### **Forecasting using Feed Foward Neural network**"""

alpha <- 1.5^(-10)
hn <- length(Cl(gsachs))/(alpha*(length(Cl(gsachs))+30)) # calculating number of hidden nodes

lambda <- BoxCox.lambda(Cl(gsachs))
dnn_pred <- nnetar(Cl(gsachs), size= hn, lambda = lambda) # Single layer dnn

dnn_forecast <- forecast(dnn_pred, h= 30, PI = TRUE)
options(repr.plot.width = 30, repr.plot.height = 10)
plot(dnn_forecast)