# # -*- coding: utf-8 -*-
# """Stock Market Analysis_Exploratory Data Analysis.ipynb
# 
# Automatically generated by Colaboratory.
# 
# Original file is located at
#     https://colab.research.google.com/drive/1UcqbC2dXkg5jf5ZiNaVeUeaG-k9mTg0A
# 
# ### **INSTALLING PACKAGES**
# """

install.packages("quantmod")
install.packages("ggplot2")

library(quantmod)
library(ggplot2)
library(dplyr)

# """### **GETTING INFO FROM QUANTMOD LIBRARY FOR GOLDMAN SACHS**"""

gsachs <- getSymbols("GS", src = "yahoo", from = "2016-01-01", to = as.character(Sys.Date()), auto.assign = FALSE)
class(gsachs)
summary(gsachs)

# """### **GRAPH FOR OPENING OF EACH DAY OVER 2016 - TODAYS DATE**"""

options(repr.plot.width = 25, repr.plot.height = 10)
ggplot(gsachs, 
  aes(x = index(gsachs), y = gsachs[,1])) + 
  geom_line(color = "darkblue") + 
  ggtitle("Goldman Sachs Group Inc : OPEN") + 
  xlab("Date") + ylab("Price") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_date(date_labels = "%b %y", 
  date_breaks = "6 months")

# """### **GRAPH FOR HIGH OF EACH DAY OVER 2016 - TODAYS DATE**"""

options(repr.plot.width = 25, repr.plot.height = 10)
ggplot(gsachs, 
  aes(x = index(gsachs), y = gsachs[,2])) + 
  geom_line(color = "darkblue") + 
  ggtitle("Goldman Sachs Group Inc : HIGH") + 
  xlab("Date") + ylab("Price") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_date(date_labels = "%b %y", 
  date_breaks = "6 months")

# """### **GRAPH FOR LOW OF EACH DAY OVER 2016 - TODAYS DATE**"""

options(repr.plot.width = 25, repr.plot.height = 10)
ggplot(gsachs, 
  aes(x = index(gsachs), y = gsachs[,3])) + 
  geom_line(color = "darkblue") + 
  ggtitle("Goldman Sachs Group Inc : LOW") + 
  xlab("Date") + ylab("Price") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_date(date_labels = "%b %y", 
  date_breaks = "6 months")

# """### **GRAPH FOR CLOSING OF EACH DAY OVER 2016 - TODAYS DATE**"""

options(repr.plot.width = 25, repr.plot.height = 10)
ggplot(gsachs, 
  aes(x = index(gsachs), y = gsachs[,4])) + 
  geom_line(color = "darkblue") + 
  ggtitle("Goldman Sachs Group Inc : CLOSE") + 
  xlab("Date") + ylab("Price") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_date(date_labels = "%b %y", 
  date_breaks = "6 months")

# """### **GRAPH FOR VOLUME OF EACH DAY OVER 2016 - TODAYS DATE**"""

options(repr.plot.width = 25, repr.plot.height = 10)
ggplot(gsachs, 
  aes(x = index(gsachs), y = gsachs[,5])) + 
  geom_line(color = "darkblue") + 
  ggtitle("Goldman Sachs Group Inc : VOLUME") + 
  xlab("Date") + ylab("Price") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_date(date_labels = "%b %y", 
  date_breaks = "6 months")

# """### **GRAPH FOR ADJUSTED OF EACH DAY OVER 2016 - TODAYS DATE**"""

options(repr.plot.width = 25, repr.plot.height = 10)
ggplot(gsachs, 
  aes(x = index(gsachs), y = gsachs[,6])) + 
  geom_line(color = "darkblue") + 
  ggtitle("Goldman Sachs Group Inc : ADJUSTED") + 
  xlab("Date") + ylab("Price") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  scale_x_date(date_labels = "%b %y", 
  date_breaks = "6 months")

# """### **CHARTS FOR OVERALL STOCK ANALYSIS FOR EACH YEAR (2016-2020)**
# 
# A **Bollinger Band**® is a technical analysis tool defined by a set of trendlines plotted two standard deviations (positively and negatively) away from a simple moving average (SMA) of a security's price, but which can be adjusted to user preferences.
# 
# --------------------------------------------------------------------------------
# 
# **Momentum** is the speed or velocity of price changes in a stock, security, or tradable instrument. Momentum shows the rate of change in price movement over a period of time to help investors determine the strength of a trend. Stocks that tend to move with the strength of momentum are called momentum stocks.
# 
# --------------------------------------------------------------------------------
# 
# The Price **Rate of Change (ROC)** is a momentum-based technical indicator that measures the percentage change in price between the current price and the price a certain number of periods ago.
# """

chartSeries(gsachs,
            type="line",
            subset="2016",
            theme=chartTheme('white'),
            name="Goldman Sachs Group Inc 2016")
addBBands(n=20,sd=2)
addMomentum(n=1)
addROC(n=7)

chartSeries(gsachs,
            type="line",
            subset="2017",
            theme=chartTheme('white'),
            name="Goldman Sachs Group Inc 2017")
addBBands(n=20,sd=2)
addMomentum(n=1)
addROC(n=7)

chartSeries(gsachs,
            type="line",
            subset="2018",
            theme=chartTheme('white'),
            name="Goldman Sachs Group Inc 2018")
addBBands(n=20,sd=2)
addMomentum(n=1)
addROC(n=7)

chartSeries(gsachs,
            type="line",
            subset="2019",
            theme=chartTheme('white'),
            name="Goldman Sachs Group Inc 2019")
addBBands(n=20,sd=2)
addMomentum(n=1)
addROC(n=7)

chartSeries(gsachs,
            type="line",
            subset="2020",
            theme=chartTheme('white'),
            name="Goldman Sachs Group Inc 2020")
addBBands(n=20,sd=2)
addMomentum(n=1)
addROC(n=7)